"""Second Migration

Revision ID: ff5cf709fbb2
Revises: b7f5e80098cf
Create Date: 2023-10-28 19:29:15.516970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff5cf709fbb2'
down_revision = 'b7f5e80098cf'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pembeli',
    sa.Column('pembeli_id', sa.Integer(), nullable=False),
    sa.Column('pembeli_nama', sa.Text(), nullable=True),
    sa.Column('pembeli_kontak', sa.Text(), nullable=True),
    sa.Column('pembeli_alamat', sa.Text(), nullable=True),
    sa.Column('pembeli_pesan', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('pembeli_id', name=op.f('pk_pembeli'))
    )
    op.create_table('produk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.Text(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('harga', sa.Text(), nullable=False),
    sa.Column('gambar', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_produk'))
    )
    op.drop_index('my_index', table_name='models', mysql_length={'name': 255})
    op.drop_table('models')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.TEXT(), nullable=True),
    sa.Column('value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('my_index', 'models', ['name'], unique=False, mysql_length={'name': 255})
    op.drop_table('produk')
    op.drop_table('pembeli')
    # ### end Alembic commands ###
